enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  '@tiptap/extension-bubble-menu@*':
    peerDependencies:
      prosemirror-commands: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-transform: '*'
  '@tiptap/react@*':
    peerDependencies:
      prosemirror-commands: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-state: '*'
      prosemirror-transform: '*'
  '@tiptap/starter-kit@*':
    dependencies:
      prosemirror-dropcursor: 1.5.0
    peerDependencies:
      prosemirror-commands: '*'
      prosemirror-gapcursor: '*'
      prosemirror-history: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-state: '*'
      prosemirror-transform: '*'
      prosemirror-view: '*'
  next-sanity@*:
    dependencies:
      '@sanity/icons': '*'
      '@sanity/types': '*'
      '@sanity/ui': '*'
      'styled-components': '*'
      'react-is': '*'
    peerDependencies:
      'react-dom': '*'
  '@sanity/eslint-config-studio@*':
    peerDependencies:
      'eslint': '*'
  '@sanity/vision@*':
    dependencies:
      'react-dom': '*'
      'react-is': '*'
      'styled-components': '*'
  'sanity@*':
    dependencies:
      'styled-components': '*'
  '@sanity/portable-text-editor@*':
    dependencies:
      'react-dom': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
